Repository typelevel/kittens, pull requests merged in 2019-06, with the labels that each got.

#152 Rework PartialOrder derivation
  core/src/main/scala/cats/derived/package.scala
  core/src/main/scala/cats/derived/partialOrder.scala
  core/src/test/scala/cats/derived/adtdefns.scala
  core/src/test/scala/cats/derived/partialOrder.scala
Labels: Design/refactoring

#153 Rework Order derivation
  core/src/main/scala/cats/derived/order.scala
  core/src/main/scala/cats/derived/package.scala
  core/src/test/scala/cats/derived/adtdefns.scala
  core/src/test/scala/cats/derived/order.scala
  core/src/test/scala/cats/derived/partialOrder.scala
Labels: Design/refactoring

#154 Rework Show derivation
  core/src/main/scala/cats/derived/package.scala
  core/src/main/scala/cats/derived/show.scala
  core/src/test/scala/cats/derived/show.scala
  core/src/test/scala/cats/derived/showPretty.scala
Labels: Design/refactoring

#155 Rework ShowPretty derivation
  core/src/main/scala/cats/derived/package.scala
  core/src/main/scala/cats/derived/showPretty.scala
  core/src/test/scala/cats/derived/showPretty.scala
Labels: Design/refactoring

#159 Use System.lineSeparator for ShowPretty
  core/src/main/scala/cats/derived/showPretty.scala
Labels: Bug

#157 Scala 2.13.0 and Hash derivation rework
  .travis.yml
  build.sbt
  core/src/main/scala-2.11/cats/derived/util/versionspecific.scala
  core/src/main/scala-2.12/cats/derived/util/versionspecific.scala
  core/src/main/scala-2.13/cats/derived/util/versionspecific.scala
  core/src/main/scala/cats/derived/hash.scala
  core/src/main/scala/cats/derived/package.scala
  core/src/test/scala/cats/derived/KittensSuite.scala
  core/src/test/scala/cats/derived/consk.scala
  core/src/test/scala/cats/derived/hash.scala
  project/build.properties
  project/plugins.sbt
Labels: Design/refactoring

#160 Rework Eq derivation
  core/src/main/scala/cats/derived/eq.scala
  core/src/main/scala/cats/derived/package.scala
  core/src/test/scala/cats/derived/adtdefns.scala
  core/src/test/scala/cats/derived/applicative.scala
  core/src/test/scala/cats/derived/apply.scala
  core/src/test/scala/cats/derived/eq.scala
  core/src/test/scala/cats/derived/foldable.scala
  core/src/test/scala/cats/derived/functor.scala
  core/src/test/scala/cats/derived/monoid.scala
  core/src/test/scala/cats/derived/monoidk.scala
  core/src/test/scala/cats/derived/semigroup.scala
  core/src/test/scala/cats/derived/semigroupk.scala
  core/src/test/scala/cats/derived/traverse.scala
Labels: Design/refactoring

#164 Replace symbol literals in SequenceSuite
  core/src/test/scala/cats/sequence/SequenceSuite.scala
Labels: Testing

#163 Refactor Iterable derivation
  core/src/main/scala/cats/derived/iterable.scala
  core/src/main/scala/cats/derived/package.scala
  core/src/test/scala/cats/derived/iterable.scala
Labels: Design/refactoring

#165 Refactor sequence and traverse implementations
  core/src/main/scala/cats/sequence/package.scala
  core/src/main/scala/cats/sequence/sequence.scala
  core/src/main/scala/cats/sequence/traverse.scala
  core/src/test/scala/cats/sequence/SequenceSuite.scala
  core/src/test/scala/cats/sequence/TraverseHListSuite.scala
Labels: Design/refactoring

#166 Ensure all derived typeclasses are Serializable
  core/src/main/scala-2.11/cats/derived/util/versionspecific.scala
  core/src/main/scala-2.12/cats/derived/util/versionspecific.scala
  core/src/main/scala-2.13/cats/derived/util/versionspecific.scala
  core/src/main/scala/cats/derived/hash.scala
  core/src/main/scala/cats/derived/util/liftSome.scala
  core/src/test/scala/cats/derived/KittensSuite.scala
  core/src/test/scala/cats/derived/applicative.scala
  core/src/test/scala/cats/derived/apply.scala
  core/src/test/scala/cats/derived/consk.scala
  core/src/test/scala/cats/derived/empty.scala
  core/src/test/scala/cats/derived/emptyk.scala
  core/src/test/scala/cats/derived/eq.scala
  core/src/test/scala/cats/derived/foldable.scala
  core/src/test/scala/cats/derived/functor.scala
  core/src/test/scala/cats/derived/hash.scala
  core/src/test/scala/cats/derived/monoid.scala
  core/src/test/scala/cats/derived/monoidk.scala
  core/src/test/scala/cats/derived/order.scala
  core/src/test/scala/cats/derived/partialOrder.scala
  core/src/test/scala/cats/derived/pure.scala
  core/src/test/scala/cats/derived/semigroup.scala
  core/src/test/scala/cats/derived/semigroupk.scala
  core/src/test/scala/cats/derived/show.scala
  core/src/test/scala/cats/derived/showPretty.scala
  core/src/test/scala/cats/derived/traverse.scala
  core/src/test/scala/cats/sequence/SequenceSuite.scala
Labels: Bug
