Repository typelevel/kittens, pull requests merged in 2019-09, with the labels that each got.

#178 Dependency updates
  .travis.yml
  build.sbt
  core/src/test/scala/cats/derived/KittensSuite.scala
  project/plugins.sbt
Labels: Build

#180 Make Gen[Recursive] sized for stack safety
  core/src/test/scala/cats/derived/adtdefns.scala
Labels: Bug

#184 Update sbt-sonatype to 2.6
  project/plugins.sbt
Labels: Build

#183 Update sbt to 1.3.0
  project/build.properties
Labels: Build

#188 Remove unused resolver and macro paradise dependencies
  build.sbt
Labels: Build

#187 Make Cogen[Recursive] tailrec
  core/src/test/scala/cats/derived/adtdefns.scala
Labels: Bug

#182 Derive Invariant
  core/src/main/scala/cats/derived/invariant.scala
  core/src/main/scala/cats/derived/package.scala
  core/src/test/scala/cats/derived/adtdefns.scala
  core/src/test/scala/cats/derived/invariant.scala
Labels: Feature
