Repository typelevel/kittens, pull requests merged in 2020-04, with the labels that each got.

#232 Update sbt to 1.3.10
  project/build.properties
Labels: Build

#221 Add CommutativeSemigroup and CommutativeMonoid derivation
  README.md
  core/src/main/scala/cats/derived/commutativeMonoid.scala
  core/src/main/scala/cats/derived/commutativeSemigroup.scala
  core/src/main/scala/cats/derived/package.scala
  core/src/test/scala/cats/derived/adtdefns.scala
  core/src/test/scala/cats/derived/commutativeMonoid.scala
  core/src/test/scala/cats/derived/commutativeSemigroup.scala
  core/src/test/scala/cats/derived/semigroup.scala
Labels: Feature

#223 Add instances for functions of all arities
  core/src/main/scala/cats/derived/function.scala
  core/src/main/scala/cats/derived/util/fnGeneric.scala
  core/src/test/scala/cats/derived/function.scala
Labels: Feature

#234 Fixes typo artefacts -> artifacts
  README.md
Labels: Documentation

#235 Scala 2.13.2
  .travis.yml
  build.sbt
  core/src/test/scala/cats/sequence/SequenceSuite.scala
Labels: Build
