Repository typelevel/kittens, pull requests merged in 2021-04, with the labels that each got.

#318 Migrate to MUnit
  build.sbt
  core/src/test/scala/cats/derived/KittensSuite.scala
  core/src/test/scala/cats/derived/consk.scala
  core/src/test/scala/cats/derived/empty.scala
  core/src/test/scala/cats/lift/LiftSuite.scala
  core/src/test/scala/cats/replicateH/ReplicateHSuite.scala
  core/src/test/scala/cats/sequence/SequenceSuite.scala
  core/src/test/scala/cats/sequence/TraverseHListSuite.scala
Labels: Testing

#319 Scala Native support
  .github/workflows/ci.yml
  build.sbt
  core/src/test/scala/cats/derived/empty.scala
  project/plugins.sbt
Labels: Build

#320 Set versionScheme, update Readme, bump MiMa version
  README.md
  build.sbt
Labels: Build

#215 Add parSequence for hlists
  core/src/main/scala/cats/sequence/sequence.scala
  core/src/main/scala/cats/sequence/traverse.scala
  core/src/test/scala/cats/sequence/SequenceSuite.scala
  core/src/test/scala/cats/sequence/TraverseSuite.scala
Labels: Feature

#323 Use SAM in generic coproduct ShowPretty derivation
  core/src/main/scala/cats/derived/showPretty.scala
Labels: Design/refactoring
